// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Parse(arg1) {
  return window['go']['main']['App']['Parse'](arg1);
}
